In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split

In [2]:
df_train = pd.read_csv('train.csv')

In [3]:
df_train.head()

,Deal_title,Lead_name,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Contact_no,Lead_revenue,Fund_category,...,Designation,Lead_POC_email,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
0,TitleM5DZY,"Davis, Perkins and Bishop Inc",Restaurants,320506$,2067263.7$,2020-03-29,Product_2,607.447.7883,50 - 100 Million,Category 2,...,Executive Vice President,charlenewerner@davis.com,Community pharmacist,Website,Level 3,No track,"Davis,Sharrice A",NaN,3,73.6
1,TitleKIW18,Bender PLC LLC,Construction Services,39488$,240876.8$,2019-07-10,Product_2,892-938-9493,500 Million - 1 Billion,Category 4,...,Chairman/CEO/President,terrylogan@bender.com,Recruitment consultant,Others,Level 1,Did not hear back after Level 1,"Brown,Maxine A",No,5,58.9
2,TitleFXSDN,Carter-Henry and Sons,Hospitals/Clinics,359392$,2407926.4$,2019-07-27,Product_1,538.748.2271,500 Million - 1 Billion,Category 4,...,SVP/General Counsel,arielhamilton@carterhenry.com,Health service manager,Marketing Event,Level 1,?,"Georgakopoulos,Vasilios T",No,4,68.8
3,TitlePSK4Y,Garcia Ltd Ltd,Real Estate,76774$,468321.4$,2021-01-30,Product_2,(692)052-1389x75188,500 Million - 1 Billion,Category 3,...,CEO/Co-Founder/Chairman,erinwilson@garcia.com,"Therapist, speech and language",Contact Email,Level 2,Did not hear back after Level 1,"Brown,Maxine A",We have all the requirements,1,64.5
4,Title904GV,Lee and Sons PLC,Financial Services,483896$,NaN,2019-05-22,Product_2,001-878-814-6134x015,50 - 100 Million,Category 3,...,Executive Vice President,mr.christopher@lee.com,Media planner,Website,Level 2,Up-to-date,"Thomas,Lori E",No,4,62.4

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7007 entries, 0 to 7006
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Deal_title             7007 non-null   object
 1   Lead_name              7007 non-null   object
 2   Industry               7006 non-null   object
 3   Deal_value             6956 non-null   object
 4   Weighted_amount        6482 non-null   object
 5   Date_of_creation       7007 non-null   object
 6   Pitch                  7007 non-null   object
 7   Contact_no             7007 non-null   object
 8   Lead_revenue           7007 non-null   object
 9   Fund_category          7007 non-null   object
 10  Geography              6035 non-null   object
 11  Location               6996 non-null   object
 12  POC_name               6999 non-null   object
 13  Designation            7007 non-null   object
 14  Lead_POC_email         7007 non-null   object
 15  Hiring_candidate_role  7007 non-null   object
 16  Lead_source            7007 non-null   object
 17  Level_of_meeting       7007 non-null   object
 18  Last_lead_update       6374 non-null   object
 19  Internal_POC           7007 non-null   object
 20  Resource               6858 non-null   object
 21  Internal_rating        7007 non-null   int64
 22  Success_probability    7007 non-null   float64
dtypes: float64(1), int64(1), object(21)
memory usage: 1.2+ MB

In [5]:
df_test = pd.read_csv('test.csv')

In [6]:
df_test.head()

,Deal_title,Lead_name,Industry,Deal_value,Weighted_amount,Date_of_creation,Pitch,Contact_no,Lead_revenue,Fund_category,...,POC_name,Designation,Lead_POC_email,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating
0,TitleAD16O,Bonilla Ltd Inc,Investment Bank/Brokerage,200988$,NaN,2020-04-15,Product_1,167.332.2751x989,100 - 500 Million,Category 4,...,sonia,Chairman/CEO/President,maureenthomas@bonilla.com,"Designer, fashion/clothing",Marketing Event,Level 1,more than a month,"Massiah,Gerard F",No,-1.0
1,TitleOW6CR,"Williams, Rogers and Roach PLC",Electronics,409961$,2541758.2$,2021-01-23,Product_1,001-486-903-0711x7831,100 - 500 Million,Category 3,...,Daniel Bell,CEO/Co-Founder/Chairman,danielbell@williams.com,Horticultural consultant,Marketing Event,Level 2,Up-to-date,"Smith,Keenan H",Yes,1.0
2,TitleVVJQ5,"Wood, Vaughn and Morales Ltd",Banks,434433$,3041031.0$,2020-07-19,Product_1,(393)104-2610x9723,100 - 500 Million,Category 1,...,Andrew Davis,Chairman/Chief Innovation Officer,andrewdavis@wood.com,Information officer,Marketing Event,Level 2,Did not hear back after Level 1,"Gilley,Janine",Deliverable,5.0
3,TitleUS8NA,Durham-Crawford Inc,Music,218952$,1521716.4$,2020-02-27,Product_2,(817)040-4599,100 - 500 Million,Category 1,...,shital,CEO/Chairman/President,charlesrivera@durhamcrawford.com,Commercial/residential surveyor,Contact Email,Level 3,more than a month,"Morsy,Omar A",No,5.0
4,Title5VGWW,"Simpson, Duncan and Long LLC",Real Estate,392835$,2455218.75$,2020-10-25,Product_1,718-032-5726x76098,500 Million - 1 Billion,Category 3,...,Shelly Stephenson,CEO/Co-Founder/Chairman,shellystephenson@simpson.com,Wellsite geologist,Others,Level 3,More than 2 weeks,"Morsy,Omar A",Deliverable,2.0

In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2093 entries, 0 to 2092
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Deal_title             2093 non-null   object
 1   Lead_name              2093 non-null   object
 2   Industry               2092 non-null   object
 3   Deal_value             2088 non-null   object
 4   Weighted_amount        2033 non-null   object
 5   Date_of_creation       2093 non-null   object
 6   Pitch                  2093 non-null   object
 7   Contact_no             2093 non-null   object
 8   Lead_revenue           2093 non-null   object
 9   Fund_category          2093 non-null   object
 10  Geography              2014 non-null   object
 11  Location               2090 non-null   object
 12  POC_name               2091 non-null   object
 13  Designation            2093 non-null   object
 14  Lead_POC_email         2093 non-null   object
 15  Hiring_candidate_role  2093 non-null   object
 16  Lead_source            2093 non-null   object
 17  Level_of_meeting       2093 non-null   object
 18  Last_lead_update       1925 non-null   object
 19  Internal_POC           2093 non-null   object
 20  Resource               2079 non-null   object
 21  Internal_rating        2093 non-null   float64
dtypes: float64(1), object(21)
memory usage: 359.9+ KB

In [8]:
for i in df_train.columns:
    print("The number of unique values in {} is {}".format(i, len(df_train[i].unique())))

The number of unique values in Deal_title is 7007
The number of unique values in Lead_name is 7007
The number of unique values in Industry is 172
The number of unique values in Deal_value is 6908
The number of unique values in Weighted_amount is 6481
The number of unique values in Date_of_creation is 777
The number of unique values in Pitch is 2
The number of unique values in Contact_no is 7007
The number of unique values in Lead_revenue is 3
The number of unique values in Fund_category is 4
The number of unique values in Geography is 3
The number of unique values in Location is 598
The number of unique values in POC_name is 5262
The number of unique values in Designation is 10
The number of unique values in Lead_POC_email is 7007
The number of unique values in Hiring_candidate_role is 639
The number of unique values in Lead_source is 4
The number of unique values in Level_of_meeting is 3
The number of unique values in Last_lead_update is 12
The number of unique values in Internal_POC is 60
The number of unique values in Resource is 7
The number of unique values in Internal_rating is 5
The number of unique values in Success_probability is 248

In [9]:
for i in df_test.columns:
    print("The number of unique values in {} is {}".format(i, len(df_test[i].unique())))

The number of unique values in Deal_title is 2093
The number of unique values in Lead_name is 2093
The number of unique values in Industry is 139
The number of unique values in Deal_value is 2084
The number of unique values in Weighted_amount is 2034
The number of unique values in Date_of_creation is 720
The number of unique values in Pitch is 2
The number of unique values in Contact_no is 2093
The number of unique values in Lead_revenue is 3
The number of unique values in Fund_category is 4
The number of unique values in Geography is 3
The number of unique values in Location is 566
The number of unique values in POC_name is 1746
The number of unique values in Designation is 10
The number of unique values in Lead_POC_email is 2093
The number of unique values in Hiring_candidate_role is 618
The number of unique values in Lead_source is 4
The number of unique values in Level_of_meeting is 3
The number of unique values in Last_lead_update is 12
The number of unique values in Internal_POC is 60
The number of unique values in Resource is 7
The number of unique values in Internal_rating is 7

In [10]:
train = df_train.drop(["Lead_name","Contact_no","POC_name","Lead_POC_email","Date_of_creation"], axis=1)
test = df_test.drop(["Lead_name","Contact_no","POC_name","Lead_POC_email","Date_of_creation"], axis=1)

In [11]:
train.isnull().sum()

Deal_title                 0
Industry                   1
Deal_value                51
Weighted_amount          525
Pitch                      0
Lead_revenue               0
Fund_category              0
Geography                972
Location                  11
Designation                0
Hiring_candidate_role      0
Lead_source                0
Level_of_meeting           0
Last_lead_update         633
Internal_POC               0
Resource                 149
Internal_rating            0
Success_probability        0
dtype: int64

In [12]:
test.isnull().sum()

Deal_title                 0
Industry                   1
Deal_value                 5
Weighted_amount           60
Pitch                      0
Lead_revenue               0
Fund_category              0
Geography                 79
Location                   3
Designation                0
Hiring_candidate_role      0
Lead_source                0
Level_of_meeting           0
Last_lead_update         168
Internal_POC               0
Resource                  14
Internal_rating            0
dtype: int64

In [13]:
train=train.replace('\$','',regex=True)

In [14]:
test = test.replace('\$', '', regex=True)

In [15]:
train = train.set_index('Deal_title')

In [16]:
train.head()

,Industry,Deal_value,Weighted_amount,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
Deal_title,,,,,,,,,,,,,,,,,
TitleM5DZY,Restaurants,320506,2067263.7,Product_2,50 - 100 Million,Category 2,USA,"Killeen-Temple, TX",Executive Vice President,Community pharmacist,Website,Level 3,No track,"Davis,Sharrice A",NaN,3,73.6
TitleKIW18,Construction Services,39488,240876.8,Product_2,500 Million - 1 Billion,Category 4,India,Ratlam,Chairman/CEO/President,Recruitment consultant,Others,Level 1,Did not hear back after Level 1,"Brown,Maxine A",No,5,58.9
TitleFXSDN,Hospitals/Clinics,359392,2407926.4,Product_1,500 Million - 1 Billion,Category 4,USA,"Albany-Schenectady-Troy, NY",SVP/General Counsel,Health service manager,Marketing Event,Level 1,?,"Georgakopoulos,Vasilios T",No,4,68.8
TitlePSK4Y,Real Estate,76774,468321.4,Product_2,500 Million - 1 Billion,Category 3,USA,"Mount Vernon-Anacortes, WA",CEO/Co-Founder/Chairman,"Therapist, speech and language",Contact Email,Level 2,Did not hear back after Level 1,"Brown,Maxine A",We have all the requirements,1,64.5
Title904GV,Financial Services,483896,NaN,Product_2,50 - 100 Million,Category 3,India,Shimoga,Executive Vice President,Media planner,Website,Level 2,Up-to-date,"Thomas,Lori E",No,4,62.4

In [17]:
test = test.set_index('Deal_title')

In [18]:
test.head()

,Industry,Deal_value,Weighted_amount,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating
Deal_title,,,,,,,,,,,,,,,,
TitleAD16O,Investment Bank/Brokerage,200988,NaN,Product_1,100 - 500 Million,Category 4,India,Bhubaneshwar,Chairman/CEO/President,"Designer, fashion/clothing",Marketing Event,Level 1,more than a month,"Massiah,Gerard F",No,-1.0
TitleOW6CR,Electronics,409961,2541758.2,Product_1,100 - 500 Million,Category 3,USA,"Coeur d'Alene, ID",CEO/Co-Founder/Chairman,Horticultural consultant,Marketing Event,Level 2,Up-to-date,"Smith,Keenan H",Yes,1.0
TitleVVJQ5,Banks,434433,3041031.0,Product_1,100 - 500 Million,Category 1,USA,"Portland-South Portland, ME",Chairman/Chief Innovation Officer,Information officer,Marketing Event,Level 2,Did not hear back after Level 1,"Gilley,Janine",Deliverable,5.0
TitleUS8NA,Music,218952,1521716.4,Product_2,100 - 500 Million,Category 1,India,Bareilly,CEO/Chairman/President,Commercial/residential surveyor,Contact Email,Level 3,more than a month,"Morsy,Omar A",No,5.0
Title5VGWW,Real Estate,392835,2455218.75,Product_1,500 Million - 1 Billion,Category 3,USA,"Trenton, NJ",CEO/Co-Founder/Chairman,Wellsite geologist,Others,Level 3,More than 2 weeks,"Morsy,Omar A",Deliverable,2.0

In [19]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7007 entries, TitleM5DZY to TitleKXU3H
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Industry               7006 non-null   object
 1   Deal_value             6956 non-null   object
 2   Weighted_amount        6482 non-null   object
 3   Pitch                  7007 non-null   object
 4   Lead_revenue           7007 non-null   object
 5   Fund_category          7007 non-null   object
 6   Geography              6035 non-null   object
 7   Location               6996 non-null   object
 8   Designation            7007 non-null   object
 9   Hiring_candidate_role  7007 non-null   object
 10  Lead_source            7007 non-null   object
 11  Level_of_meeting       7007 non-null   object
 12  Last_lead_update       6374 non-null   object
 13  Internal_POC           7007 non-null   object
 14  Resource               6858 non-null   object
 15  Internal_rating        7007 non-null   int64
 16  Success_probability    7007 non-null   float64
dtypes: float64(1), int64(1), object(15)
memory usage: 985.4+ KB

In [20]:
train['Weighted_amount'] = pd.to_numeric(train['Weighted_amount'], errors='coerce')
train['Deal_value'] = pd.to_numeric(train['Deal_value'], errors='coerce')
test['Weighted_amount'] = pd.to_numeric(test['Weighted_amount'], errors='coerce')
test['Deal_value'] = pd.to_numeric(test['Deal_value'], errors='coerce')

In [21]:
train["Industry"].fillna(train["Industry"].mode()[0], inplace = True)
test["Industry"].fillna(test["Industry"].mode()[0], inplace = True)

In [22]:
train["Last_lead_update"].fillna(train["Last_lead_update"].mode()[0], inplace = True)
test["Last_lead_update"].fillna(test["Last_lead_update"].mode()[0], inplace = True)

In [23]:
train["Resource"].fillna(train["Resource"].mode()[0], inplace = True)
test["Resource"].fillna(test["Resource"].mode()[0], inplace = True)

In [24]:
train['Deal_value'].fillna(train['Deal_value'].median(), inplace=True)
test['Deal_value'].fillna(test['Deal_value'].median(), inplace=True)

In [25]:
train['Weighted_amount'].fillna(train['Weighted_amount'].median(), inplace=True)
test['Weighted_amount'].fillna(test['Weighted_amount'].median(), inplace=True)

In [26]:
train['Geography'].value_counts(dropna=False)

USA      3061
India    2974
NaN       972
Name: Geography, dtype: int64

In [27]:
train[train['Geography'].isnull()]

,Industry,Deal_value,Weighted_amount,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
Deal_title,,,,,,,,,,,,,,,,,
TitleOZQRY,Banks,384356.0,2709709.80,Product_2,500 Million - 1 Billion,Category 1,NaN,"Salisbury, MD-DE",CEO/Co-Founder/Chairman,Cartographer,Contact Email,Level 3,More than 2 weeks,"Booker,David L",No,4,73.40
TitleP5EAQ,Healthcare Facilities/Services,311125.0,1851193.75,Product_1,500 Million - 1 Billion,Category 2,NaN,"Oxnard-Thousand Oaks-Ventura, CA",CEO/Co-Founder/Chairman,Hydrogeologist,Website,Level 1,Following up but lead not responding,"Clavey,Therese A",Cannot deliver,2,67.90
TitleNQKU6,Banks,487351.0,1548238.95,Product_1,500 Million - 1 Billion,Category 3,NaN,Pilibhit,Chairman/Chief Innovation Officer,Hospital doctor,Marketing Event,Level 3,More than a week back,"Shelton,Sidney P",We have all the requirements,2,26.35
TitleBZ8I3,Other Investment Firms,390309.0,2458946.70,Product_2,50 - 100 Million,Category 2,NaN,"Miami-Fort Lauderdale-West Palm Beach, FL",Chairman/CEO/President,Broadcast journalist,Contact Email,Level 3,?,"Dimattia,Frank D",Deliverable,4,70.00
TitleWKMYP,Trucking,380817.0,2513392.20,Product_2,50 - 100 Million,Category 1,NaN,"Chambersburg-Waynesboro, PA",CEO/President,Armed forces operational officer,Contact Email,Level 3,Did not hear back after Level 1,"Leu,Darren L",No,1,68.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Title6RJU9,Water Utilities,242256.0,1707904.80,Product_2,500 Million - 1 Billion,Category 1,NaN,"Shreveport-Bossier City, LA",SVP/General Counsel,"Engineer, automotive",Marketing Event,Level 3,Pending,"Robinson,John C",No,1,73.50
TitlePROWH,Financial Services,31429.0,220003.00,Product_2,500 Million - 1 Billion,Category 4,NaN,"Knoxville, TN",CEO/Co-Founder/Chairman,Applications developer,Website,Level 3,Up-to-date,"Young,Valerie K",Deliverable,4,70.50
TitleIP4T5,Beverages (Alcoholic),152908.0,970965.80,Product_1,100 - 500 Million,Category 1,NaN,Kohima,CEO/President,Counselling psychologist,Website,Level 2,5 days back,"Gould,Lisa D",No,1,62.70
TitleJ7TDY,Banks,192800.0,1195360.00,Product_1,100 - 500 Million,Category 4,NaN,Kagaznagar,CEO/Co-Founder/Chairman,Call centre manager,Contact Email,Level 1,More than a week back,"Jones,Eyvette W",We have all the requirements,4,107.34
TitleO1IIN,Hospitals/Clinics,220208.0,1453372.80,Product_2,100 - 500 Million,Category 1,NaN,Proddatur,CEO,Financial risk analyst,Marketing Event,Level 2,?,"Brown,Maxine A",We have all the requirements,3,26.35

# we can understand from the above data is that the area from USA has a , in between them but areas from India doesn't have them. So, we can fillup the Gerography with USA where the area has a , and the one which doesn't have a , as India,

In [28]:
train[['Place', 'State']] = train['Location'].str.split(' ', 1, expand=True)
train['State'].fillna('0', inplace = True)
train['Geography'].fillna('USA', inplace = True)
train.loc[train['State'] == '0', 'Geography'] = 'India'
train.drop(['Place', 'State'], axis = 1, inplace = True)

In [29]:
test[['Place', 'State']] = train['Location'].str.split(' ', 1, expand=True)
test['State'].fillna('0', inplace = True)
test['Geography'].fillna('USA', inplace = True)
test.loc[test['State'] == '0', 'Geography'] = 'India'
test.drop(['Place', 'State'], axis = 1, inplace = True)

In [30]:
train[train['Location'].isnull()]

,Industry,Deal_value,Weighted_amount,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
Deal_title,,,,,,,,,,,,,,,,,
TitleY3XZP,Investment Bank/Brokerage,321315.0,2056416.00,Product_1,100 - 500 Million,Category 1,India,NaN,SVP/General Counsel,"Nurse, learning disability",Contact Email,Level 2,More than 2 weeks,"McKenstry,Loretta A",Not enough,1,66.10
TitleE0MD4,REIT,457184.0,3108851.20,Product_1,50 - 100 Million,Category 1,India,NaN,CEO/Co-Founder/Chairman,Pharmacologist,Others,Level 3,Up-to-date,"Salyers,Daniel L",Cannot deliver,5,74.90
TitleX2NTQ,Insurance,134465.0,793343.50,Product_1,500 Million - 1 Billion,Category 3,India,NaN,Chairman/CEO/President,Radio broadcast assistant,Others,Level 2,Following up but lead not responding,"Mabrey,Kevin C",Yes,1,65.80
Title4AI1N,Banks,380753.0,2684308.65,Product_1,500 Million - 1 Billion,Category 3,India,NaN,CEO/Chairman/President,Arts development officer,Marketing Event,Level 3,Up-to-date,"Jones,Michael L",Not enough,5,26.35
TitleT9KKE,Telecom Consulting,383929.0,2687503.00,Product_2,50 - 100 Million,Category 4,India,NaN,Vice President / GM (04-present) : VP Sales an...,Dance movement psychotherapist,Contact Email,Level 3,Up-to-date,"Ali,Mohamed",Cannot deliver,5,70.10
TitleQF35M,Investment Bank/Brokerage,37105.0,222630.00,Product_2,500 Million - 1 Billion,Category 2,India,NaN,Chairman/CEO/President,General practice doctor,Marketing Event,Level 2,Following up but lead not responding,"Bannister,Joan",No,1,107.34
TitleHI98X,Architecture/Engineering,485381.0,3252052.70,Product_2,500 Million - 1 Billion,Category 4,India,NaN,Chairman/CEO/President,Television production assistant,Contact Email,Level 2,Up-to-date,"Cashin,Marc C",Yes,3,107.34
TitleK42F3,Other Biz Services,15638.0,103992.70,Product_2,50 - 100 Million,Category 4,India,NaN,Chairman/Chief Innovation Officer,"Conservator, museum/gallery",Marketing Event,Level 2,5 days back,"Van Arter,Derrick",Not enough,5,67.70
TitleOSYEE,Staffing,449933.0,2924564.50,Product_2,500 Million - 1 Billion,Category 4,India,NaN,CEO/Co-Founder/Chairman,Multimedia specialist,Contact Email,Level 1,Following up but lead not responding,"Featherstone,Adrian R",No,4,65.50
Title9V907,Financial Services,164299.0,1026868.75,Product_1,100 - 500 Million,Category 2,India,NaN,Executive Vice President,"Engineer, civil (contracting)",Others,Level 3,No track,"Pappas,Mark S",Cannot deliver,4,71.80
Title70QKM,Banks,63427.0,396418.75,Product_2,100 - 500 Million,Category 3,India,NaN,CEO/Chairman/President,Information officer,Website,Level 2,More than a week back,"Davis,Sharrice A",Deliverable,3,67.90

In [31]:
train.drop(train.loc[train['Success_probability']>100].index, inplace=True)

In [32]:
train.nunique()

Industry                  171
Deal_value               6409
Weighted_amount          6014
Pitch                       2
Lead_revenue                3
Fund_category               4
Geography                   2
Location                  597
Designation                10
Hiring_candidate_role     639
Lead_source                 4
Level_of_meeting            3
Last_lead_update           11
Internal_POC               60
Resource                    6
Internal_rating             5
Success_probability       247
dtype: int64

In [33]:
# Get list of categorical variables
s = (train.dtypes == 'object')
object_cols = list(s[s].index)
print(object_cols)

['Industry', 'Pitch', 'Lead_revenue', 'Fund_category', 'Geography', 'Location', 'Designation', 'Hiring_candidate_role', 'Lead_source', 'Level_of_meeting', 'Last_lead_update', 'Internal_POC', 'Resource']

In [34]:
for i in object_cols :
    train[i] = train[i].astype('category')
    test[i] = test[i].astype('category')
#coverting the categorical columns to numeric
# Apply label encoder to each column with categorical data
label_encoder = LabelEncoder()
for col in object_cols:
    train[col] = label_encoder.fit_transform(train[col].astype(str))
    test[col] = label_encoder.fit_transform(test[col].astype(str))

In [35]:
train.head()

,Industry,Deal_value,Weighted_amount,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating,Success_probability
Deal_title,,,,,,,,,,,,,,,,,
TitleM5DZY,119,320506.0,2067263.70,1,1,1,1,292,7,126,3,2,7,12,2,3,73.6
TitleKIW18,31,39488.0,240876.80,1,2,3,0,457,4,501,2,0,3,5,2,5,58.9
TitleFXSDN,56,359392.0,2407926.40,0,2,3,1,15,8,286,1,0,2,18,2,4,68.8
TitlePSK4Y,114,76774.0,468321.40,1,2,2,1,372,2,611,0,1,3,5,4,1,64.5
Title904GV,46,483896.0,1548238.95,1,1,2,0,505,7,369,3,1,9,53,2,4,62.4

In [36]:
y = train.pop('Success_probability')
X = train

In [39]:
y

Deal_title
TitleM5DZY    73.60
TitleKIW18    58.90
TitleFXSDN    68.80
TitlePSK4Y    64.50
Title904GV    62.40
              ...
TitleAQSP7    57.40
TitleO1IIN    26.35
TitleF1FWY    70.60
TitleXVBNJ    -5.00
TitleKXU3H    68.70
Name: Success_probability, Length: 6492, dtype: float64

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [95]:
from sklearn.ensemble import RandomForestRegressor

In [97]:
rfr = RandomForestRegressor(n_estimators=250)
rfr.fit(X_train, y_train)

RandomForestRegressor(n_estimators=250)

In [98]:
predictions = rfr.predict(X_test)

In [46]:
X_train

,Industry,Deal_value,Weighted_amount,Pitch,Lead_revenue,Fund_category,Geography,Location,Designation,Hiring_candidate_role,Lead_source,Level_of_meeting,Last_lead_update,Internal_POC,Resource,Internal_rating
Deal_title,,,,,,,,,,,,,,,,
TitleNJZFN,62,25839.0,170537.40,1,1,3,0,458,1,472,1,2,8,54,2,3
TitleQBLVO,56,87982.0,563084.80,1,0,1,0,474,7,508,3,2,4,42,0,4
TitleUV0RX,112,143103.0,994565.85,0,0,3,1,333,3,85,2,2,9,8,1,5
Title2IPPW,46,116436.0,768477.60,1,0,3,1,519,7,582,0,0,4,55,2,5
TitleS8IM5,17,206748.0,1302512.40,1,0,1,1,88,7,6,1,1,1,19,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TitleQ5BUS,53,195434.0,1250777.60,0,1,0,1,585,2,550,3,1,8,35,1,1
TitleS55G3,46,417763.0,2485689.85,0,2,1,0,149,8,38,3,1,4,7,0,2
TitleQSF4W,54,368139.0,2172020.10,0,1,1,1,418,3,301,2,2,6,3,5,1
TitleV7A55,17,231093.0,1675424.25,1,2,0,1,489,4,633,1,2,7,10,1,3
TitleVSS1F,48,26003.0,141716.35,1,0,1,0,338,7,329,3,0,9,47,2,2

In [99]:
score=max(0,100-np.sqrt(metrics.mean_squared_error(y_test,predictions)))
print(score)

86.38352989344486

In [100]:
final = rfr.predict(test)
test['Success_probability']= final
test = test.drop(['Industry','Deal_value','Weighted_amount','Pitch','Lead_revenue','Fund_category','Geography','Location','Designation','Hiring_candidate_role','Lead_source','Level_of_meeting','Last_lead_update','Internal_POC','Resource','Internal_rating'], axis=1)
test.to_csv('output.csv')